In [10]:
!pip install tensorflow==2.0.0-beta1

  Could not find a version that satisfies the requirement tf-nightly-2.0-preview (from versions: )
No matching distribution found for tf-nightly-2.0-preview


In [1]:
import tensorflow as tf
tf.enable_eager_execution=True
print (tf.__version__)

2.0.0-beta1


### Create a dataset with 10 values and print

In [18]:
dataset = tf.data.Dataset.range(10)
for val in dataset:
    print (val.numpy())

0
1
2
3
4
5
6
7
8
9


### Create window'ed data using the above dataset

In [20]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)

for window in dataset:
    for val in window:
        print (val.numpy(), end=" ")
    print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


### Create Features & Labels using the dataset

In [34]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))

for window in dataset:
    print (window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [38]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))

for x, y in dataset:
    print (x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [36]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=3)

for x, y in dataset:
    print (x.numpy(), y.numpy())

[0 1 2 3] [4]
[3 4 5 6] [7]
[1 2 3 4] [5]
[2 3 4 5] [6]
[5 6 7 8] [9]
[4 5 6 7] [8]


In [37]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift=1, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size=3)
dataset = dataset.batch(2).prefetch(1)
for x, y in dataset:
    print (x.numpy(), y.numpy())

[[2 3 4 5]
 [3 4 5 6]] [[6]
 [7]]
[[4 5 6 7]
 [5 6 7 8]] [[8]
 [9]]
[[0 1 2 3]
 [1 2 3 4]] [[4]
 [5]]
